mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('weather.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
  + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

weather/urls.py
from django.urls import path

from . import views

app_name = 'weather'
urlpatterns = [
    path('', views.home, name='home'),
    path('home/', views.home, name='home'),
    path('login/', views.login_request, name='login'),
    path('logout/', views.logout_request, name='logout'),
    path('registration/', views.registration_request, name='registration'),
    path('add-person/', views.add_person_request, name='add-person'),
    path('update-person/<int:id>/', views.update_person, name='update-person'),
    path('detail-person/<int:id>/', views.detail_person, name='detail-person'),
    path('delete-person/<int:id>/', views.delete_person, name='delete-person'),
]

weather/models.py
from datetime import date

from django.db import models
from django.conf import settings
from django.utils.timezone import now # UTC timezone (per project settings)

from .funcs import get_all_timezones

TIMEZONES = get_all_timezones()

class Location(models.Model):
    name = models.CharField(max_length=30)
    latitude = models.CharField(max_length=20)
    longitude = models.CharField(max_length=20)
    TZ_NAMES = [(name, name) for name, _ in TIMEZONES.items()]
    timezone = models.CharField(max_length=30, choices=TZ_NAMES)

class Person(models.Model):
    name = models.CharField(max_length=30)
    location = models.ForeignKey(Location, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='images/people/',
                              default='images/person_default.jpeg')

class Weather(models.Model):
    location = models.ForeignKey(Location, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(default=now)
    step = models.CharField(max_length=2)
    date = models.DateField(default=date(1970, 1, 1))
    hour = models.IntegerField(default=0)
    temp = models.IntegerField()
    weather_code = models.CharField(max_length=5)

class User_Person(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    person = models.ForeignKey(Person, on_delete=models.CASCADE)
    date_added = models.DateField(default=now)

weather/views.py
from pathlib import Path
import requests
import json
from datetime import datetime, timedelta
import pytz
import time

from django.shortcuts import  render, redirect
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.models import User
from django.core.files import File
from django.utils.timezone import now  # UTC timezone (per project settings)
from django.conf import settings

from .models import Person, Weather, User_Person, Location
from .funcs import get_codes, get_icon_path, get_timezone

# Constants
PRINT_DEBUG = True  # print statements for debugging
API_RESULT_LIFETIME = timedelta(hours=6)
# Track API requests per second to prevent exceeding limit of 3
API_REQ_PER_SEC = {}  # minute-second: requests
WEATHER_CODES, WEATHER_CODES_DAY = get_codes()
CODES = {'hour': WEATHER_CODES, 'day': WEATHER_CODES_DAY}
CODE_PARAM = {'hour': 'weatherCode', 'day': 'weatherCodeDay'}
TIMESTEPS = {'hour': '1h', 'day': '1d'}
TIMEDELTAS = {'hour': timedelta(hours=1), 'day': timedelta(days=3)}

# VIEW FUNCTIONS
def home(request):
    context = {}
    if request.user.is_authenticated:
        user = User.objects.get(username=request.user.username)
        user_persons = User_Person.objects.filter(user_id=user)
        if PRINT_DEBUG: print(f"> User: {user.username}")
        for up in user_persons:
            location = up.person.location
            local_now = datetime.now(tz=pytz.timezone(location.timezone))
            if PRINT_DEBUG: print(f"  - {up.person.name}, {location.name}")
            data = get_weather(location, local_now, 'hour')
            up.person.cur_weather = data
            local_dates = [local_now + timedelta(days=i) for i in range(3)]
            days = []
            for local_date in local_dates:
                data = get_weather(location, local_date, 'day')
                days.append(data)
            up.person.days = days
        context['people'] = user_persons
    return render(request, 'weather/home.html', context)

def login_request(request):
    context = {}
    if request.method == "POST":
        user = authenticate(username=request.POST['username'],
                            password=request.POST['password'])
        if user:
            login(request, user)
            return redirect('weather:home')
        else:
            context['message'] = "Invalid username or password."
    return render(request, 'weather/user_login.html', context)

def logout_request(request):
    logout(request)
    return redirect('weather:home')

def registration_request(request):
    context = {}
    if request.method == 'GET':
        return render(request, 'weather/user_registration.html', context)
    elif request.method == 'POST':
        username = request.POST['username']
        user_exist = False
        try:
            User.objects.get(username=username)
            user_exist = True
        except User.DoesNotExist:
            pass
        if not user_exist:
            user = User.objects.create_user(username=username,
                    first_name=request.POST['firstname'],
                    last_name=request.POST['lastname'],
                    password=request.POST['password'])
            login(request, user)
            return redirect("weather:home")
        else:
            context['message'] = "User already exists."
            return render(request, 'weather/user_registration.html', context)

def add_person_request(request):
    context = {}
    if not request.user.is_authenticated:
        return render(request, 'weather/user_login.html', context)
    if request.method == 'POST':
        latitude, longitude = request.POST['lat'], request.POST['long']
        new_location = get_location(latitude, longitude, request)
        new_person = Person.objects.create(name=request.POST['name'],
                                           location=new_location)
        new_person.save()
        add_image(request, new_person)
        new_user_person = User_Person.objects.create(person=new_person,
            user=User.objects.get(username=request.user.username))
        new_user_person.save()
        return redirect("weather:home")
    return render(request, 'weather/add_person.html', context)

def update_person(request, id):
    context = {}
    if request.method == 'POST':
        person = Person.objects.get(id=id)
        latitude, longitude = request.POST['lat'], request.POST['long']
        new_location = get_location(latitude, longitude, request)
        person.name = request.POST['name']
        person.location = new_location
        person.save()
        add_image(request, person)
        return redirect("weather:home")
    return render(context, f'weather/detail-person/{id}', context)

def detail_person(request, id):
    context = {'person': Person.objects.get(id=id)}
    return render(request, 'weather/detail_person.html', context)

def delete_person(request, id):
    person_to_delete = Person.objects.get(id=id)
    person_to_delete.delete()
    return redirect("weather:home")

# HELPER FUNCTIONS
def get_weather(location: Location, local_now: datetime, period: str) -> dict:
    data = {'temp': 'n/a', 'description': 'n/a', 'icon_path': ''}
    weather = query_database(location, local_now, period)
    if weather is None or weather.timestamp + API_RESULT_LIFETIME < now():
        if weather and weather.timestamp + API_RESULT_LIFETIME < now() and PRINT_DEBUG:
            print(f"\t  - Database record expired: Weather Obj {weather.id}")
        weather = api_request(weather, local_now, location, period)
    if weather:
        code = str(weather.weather_code)
        data['description'] = CODES[period][code]
        if period == 'hour':
            code += '0' if 6 <= local_now.hour <= 19 else '1'
        data['icon_path'] = get_icon_path(code)
        data['temp'] = int(weather.temp)
        data['day_name'] = local_now.strftime("%A")
    return data

def query_database(location: Location, local_now: datetime, period: str):
    HOURS = {'day': 0, 'hour': local_now.time().hour}
    if PRINT_DEBUG:
        print(f"    - {local_now.date()} {period} {HOURS[period]}".ljust(24), end='')
    try:
        query = Weather.objects.filter(location=location, date=local_now.date(),
                    hour=HOURS[period],step=TIMESTEPS[period])
        weather = query.order_by("-timestamp")[:1].get()
        if PRINT_DEBUG: print(f"  > Retrieved from database")
        return weather
    except Weather.DoesNotExist:
        if PRINT_DEBUG: print(f"  > Not found in database")
        return None

def api_request(weather: Weather, current_time: datetime, location: Location,
                period: str) -> Weather:
    API_BASE_URL = 'https://api.tomorrow.io/v4/timelines'
    API_KEY = 'P0upWa3NF5mlabyrkmlCDqZWDblfSUUc'
    step = TIMESTEPS[period]
    coordinates = str(location.latitude) + ',' + str(location.longitude)
    params = {'location': coordinates,
              'startTime': current_time.isoformat(),
              'endTime': (current_time + TIMEDELTAS[period]).isoformat(),
              'timesteps': step,
              'fields': ['temperature', CODE_PARAM[period]],
              'units': 'imperial',
              'apikey': API_KEY,}
    key = now().strftime('%M:%S')
    API_REQ_PER_SEC[key] = API_REQ_PER_SEC.get(key, 0) + 1
    if API_REQ_PER_SEC[key] > 3:
        print('\t- Sleeping 1 second to avoid API request limit (3 per second)')
        time.sleep(1)
    response = requests.get(API_BASE_URL, params)
    response_dict = response.json()
    if response.status_code == 200:
        intervals = response_dict['data']['timelines'][0]['intervals']
        new_weathers = []
        for interval in intervals:
            new_weather = create_weather_obj(interval, location, period,
                                             current_time, step)
            new_weathers.append(new_weather)
        if PRINT_DEBUG: print('\t> API request successful')
        save_json_response(response_dict, new_weather)
        return new_weathers[0]
    elif response.status_code == 429:
        if PRINT_DEBUG: print('\t> API request failed (429): limit reached')
        if PRINT_DEBUG: print('\t  - Message', response_dict['message'])
    elif response.status_code == 400:
        if PRINT_DEBUG: print('\t> API request failed:', response_dict['type'])
        if PRINT_DEBUG: print('\t  - Message:', response_dict['message'])
    return weather

def create_weather_obj(interval: list, location: Location, period: str,
                       current_time: datetime, step: str) -> Weather:
    time_utc = datetime.fromisoformat(interval['startTime'].replace('Z', ''))
    time_utc = time_utc.replace(tzinfo=pytz.utc)
    time_local = time_utc.astimezone(tz=current_time.tzinfo)
    HOURS = {'day': 0, 'hour': time_local.hour}
    new_weather = Weather(location=location, date=time_local.date(),
        hour=HOURS[period], temp=interval['values']['temperature'],
        weather_code=interval['values'][CODE_PARAM[period]], step=step)
    new_weather.save()
    return new_weather

def save_json_response(response: dict, weather: Weather) -> None:
    out_directory = Path(settings.STATIC_ROOT + '/weather/api-responses/')
    file_time = datetime.now().time().isoformat('seconds').replace(':','-')
    loc = weather.location.name.lower().replace(' ', '-').replace(',', '-')
    fn = f"{loc}-{weather.date}-T{weather.hour}-{weather.step}-{file_time}.json"
    if out_directory.exists():
        with open(out_directory.joinpath(fn), 'w') as f:
            json.dump(response, f, indent=4)
        if PRINT_DEBUG: print('\t> Saved API response')
    else:
        if PRINT_DEBUG: print(f"\t> API response not saved: DNE: {out_directory.absolute()}")

def get_location(lat: str, long: str, request) -> Location:
    try:
        new_location = Location.objects.get(latitude=lat, longitude=long)
    except Location.DoesNotExist:
        new_location = Location.objects.create(

weather/templates/weather/add_person.html
{% extends "weather/base.html" %}

{% block content %}
<form class="m-4" enctype="multipart/form-data" action="{% url 'weather:add-person' %}" method="post">
    {% csrf_token %}
    <div class="container">
        <h1>Add New Person</h1>
        <hr>
        <div class="form-group">
            <label for="name" class="form-label"><b>Name</b></label>
            <input type="text" class="form-control mb-4" placeholder="Enter Name: " name="name" required>

            <label for="formFile" class="form-label"><b>Image </b>(optional). Please use a small image that is approximately square.</label>
            <input type="file" class="form-control mb-4" name="formFile">

            <label for="locationName" class="form-label"><b>Location Name </b>(the way you would like to see it displayed)</label>
            <input type="text" class="form-control mb-4" name="locationName">

            <input type="hidden" id="lat" name="lat" value="38.89842698419016">
            <input type="hidden" id="long" name="long"  value="-77.03635811789901">
            <h4>Select Location</h4>
            <p>Please move the pin to the location you would like to follow. <em>In the future, we hope to provide more user-friendly options to pick a location!</em></p>
            <div id="map"></div>
            <br>
            {% load static %}
            <script src="{% static 'weather/js/map.js' %}"></script>

            {% if message %}
            <div class="alert alert-warning">
                {{ message }}
            </div>
            {% endif %}
            <button class="btn btn-primary mt-4" type="submit">Add Person</button>
        </div>
    </div>
</form>
{% endblock %}

weather/templates/weather/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>WeatherFam</title>
        {% load static %}
        <link rel="icon" type="image/x-icon" href="{% static 'images/favicon.ico' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'weather/css/bootstrap.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'weather/css/style.css' %}">
        <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key={{ google_api_key }}"></script>
        <script src="https://unpkg.com/location-picker/dist/location-picker.min.js"></script>
    </head>
    <body>
        <!-- Add Navbar -->
        <nav class="navbar navbar-custom">
            <div class="container-fluid" style="padding: 0px;">
                <div class="navbar-header">
                    <a class="navbar-brand navbar-custom" href="/">
                        <img src="{% static 'images/favicon-white.ico' %}" alt="WF" width="30" height="30" class="d-inline-block align-top mr-2">
                        WeatherFam
                    </a>
                    <a class="navbar-brand navbar-custom" href="/">Home</a>
                </div>
                <ul class="nav navbar-nav navbar-right">
                    {% if user.is_authenticated %}
                    <li>
                        <span class="btn btn-light-custom">Hi, {{ user.first_name.title }} ({{ user.username }})</span>
                        <a class="btn btn-link btn-light-custom" href="{% url 'weather:logout' %}">Logout</a>
                    </li>
                    {% else %}
                    <li>
                        <span class="input-group">
                            <form class="form-inline" action="{% url 'weather:login' %}" method="post">
                                {% csrf_token %}
                                    <input type="text" class="form-control mr-2" placeholder="Username" name="username" >
                                    <input type="password" class="form-control mr-2" placeholder="Password" name="password" >
                                    <button class="btn btn-primary mr-2" type="submit">Login</button>
                            </form>
                            <form class="form-inline" action="{% url 'weather:registration' %}" method="get">
                                {% csrf_token %}
                                <button class="btn btn-success" type="submit">Sign Up</button>
                            </form>
                        </span>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </nav>

        <!-- MAIN BODY CONTENT -->
        {% block content %}
        {% endblock %}
        
    </body>

<!-- Footer -->
<footer class="footer-custom text-center align-middle text-lg-start">
    <section class="justify-left p-4 border-bottom">
        <div class="row">
            <div class="column col-sm">Andrew Tracey, 2022.</div>
            <div class="column col-sm">Connect with me:
                <a href="https://www.linkedin.com/in/andrew-tracey/" class="me-4 mx-2" target="_blank" style="color:white; text-decoration: underline;">LinkedIn</a>
                <a href="https://github.com/andrewt110216" class="me-4" target="_blank" style="color:white; text-decoration: underline;">GitHub</a>
            </div>
            <div class="column col-sm">Powered by Tomorrow.io.</div>
        </div>
    </section>
</footer>
</html>

weather/templates/weather/detail_person.html
{% extends "weather/base.html" %}

{% block content %}


<!-- FORM FOR UPDATING PERSON DETAILS -->
<form class="m-4" enctype="multipart/form-data" action="{% url 'weather:update-person' person.id %}" method="post">
    {% csrf_token %}
    {% load static %}
    <div class="container">
        <div class="d-flex justify-content-between align-items-center mt-4">
            <span class=""><img class="card-img-left p-2" src="{% static person.image.name %}" width="100em" height="100em" alt="Profile Image"></span>
            <h2 class="">{{ person.name }}</h2>
            <div><a class="btn btn-danger" href="{% url 'weather:delete-person' person.id %}">- Delete Person</a></div>
        </div>
        <hr color=#2C3E50>
        <div class="form-group">
            <label for="name" class="form-label"><b>Name</b></label>
            <input type="text" class="form-control mb-4" value="{{ person.name }}" name="name" required>

            <label for="formFile" class="form-label"><b>Image </b>(optional). Please use a small image that is approximately square.</label>
            <input type="file" class="form-control mb-4" name="formFile">

            <label for="locationName" class="form-label"><b>Location Name </b>(the way you would like to see it displayed)</label>
            <input type="text" class="form-control mb-4" value="{{ person.location.name }}" name="locationName">

            <input type="hidden" id="lat" name="lat" value="{{ person.location.latitude }}">
            <input type="hidden" id="long" name="long"  value="{{ person.location.longitude }}">
            <h4>Select Location</h4>
            <p>Please move the pin to the desired location for {{ person.name }}. <em>In the future, we hope to provide more user-friendly options to pick a location!</em></p>
            <div id="map"></div>
            <br>
            {% load static %}
            <script src="{% static 'weather/js/map.js' %}"></script>

            {% if message %}
            <div class="alert alert-warning">
                {{ message }}
            </div>
            {% endif %}
            <button class="btn btn-primary mt-4" type="submit">Update Person</button>
        </div>
    </div>
</form>
{% endblock %}

weather/templates/weather/home.html
{% extends "weather/base.html" %}

{% block content %}
{% if user.is_authenticated %}
    <div class="d-flex justify-content-between align-items-center mt-4 mx-3">
        <h2 class="text-right">My People</h2>
        <div>
            <a class="btn btn-success" href="/add-person/">+ Add Person</a>
        </div>
    </div>

    <hr color=#2C3E50 class="mx-3">
    {% if not people %}
        <p class="m-3">Click 'Add Person' to add a loved one, a photo, and a weather location to get started!</p>
    {% else %}
    <div class="row"> <!-- Row Wrapping All Cards -->
        {% load static %}
        {% for up in people %}
        <div class="col-lg-6 col-md-12"> <!-- Grid -->
            <div class="card m-3 border-dark"> <!-- Card -->
                <div class="card-header card-header-custom"> <!-- Card Header-->
                    <div class="row align-items-center">
                        <div class="column col-sm">
                            <img class="card-img-left p-2" src="{% static up.person.image.name %}"
                                 width="100em" height="100em" alt="Profile Image">
                        </div>
                        <div class="column col-sm text-center">
                            <a class="h4 mb-1" href="{% url 'weather:detail-person' up.person.id %}">{{ up.person.name }}</a>
                            <div class="h5 font-weight-light">{{ up.person.location.name }}</div>
                        </div>
                        <div class="column col-sm text-right pr-4"> <!-- Current Weather -->
                            <div class="h4">{{ up.person.cur_weather.temp }} &deg;</div>
                            <img src="{% static up.person.cur_weather.icon_path %}" width="50em" height="50em" alt="n/a">
                            <div class="font-weight-light h6">{{ up.person.cur_weather.description }}</div>
                        </div>
                    </div>
                </div> <!-- End of Card Header -->
                <div class="card-body card-body-custom">
                    <div class="table-responsive">
                        <table class="table text-center" style="table-layout:fixed">
                            <tr> <!-- Header Row -->
                                <th class="h5">Today</th>
                                <th class="h5">{{ up.person.days.1.day_name }}</th>
                                <th class="h5">{{ up.person.days.2.day_name }}</th>
                            </tr>
                            <tr> <!-- Temperature Row -->
                                <td class="h4">{{ up.person.days.0.temp }} &deg;</td>
                                <td class="h4">{{ up.person.days.1.temp }} &deg;</td>
                                <td class="h4">{{ up.person.days.2.temp }} &deg;</td>
                            </tr>
                            <tr> <!-- Icon Row -->
                                <td class="h5">
                                    <img src="{% static up.person.days.0.icon_path %}" width="60em" height="60em" alt="n/a">
                                    <br><span class="font-weight-light h6">{{ up.person.days.0.description }}</span>
                                </td>
                                <td class="h5">
                                    <img src="{% static up.person.days.1.icon_path %}" width="60em" height="60em" alt="n/a">
                                    <br><span class="font-weight-light h6">{{ up.person.days.1.description }}</span>
                                </td>
                                <td class="h5">
                                    <img src="{% static up.person.days.2.icon_path %}" width="60em" height="60em" alt="n/a">
                                    <br><span class="font-weight-light h6">{{ up.person.days.2.description }}</span>
                                </td>
                            </tr>
                            </tr>
                        </table>
                    </div> <!-- End of Weather Table Container -->
                </div> <!-- End of Card Body -->
            </div> <!-- End of Card -->
        </div> <!-- End of Grid -->
        {% endfor %}
    {% endif %}
    </div> <!-- End of Row Wrapping All Cards -->

{% else %} <!-- If User Not Logged In -->
    <div class="container m-4">
        <h1>Welcome to WeatherFam!</h1>
        <h4 class="font-italic font-weight-light">A weather app with personality.</h4>
        <hr>
        <p>WeatherFam allows you to follow the weather in locations that matter to you and your loved ones, in a personalized way.</p>
        <p>Please log in or sign up above to begin.</p>
    </div>

{% endif %}
{% endblock %}

weather/templates/weather/user_login.html
{% extends "weather/base.html" %}

{% block content %}
<form class="m-4" action="{% url 'weather:login' %}" method="post">
    {% csrf_token %}
    <div class="container"> 
      <h1>Login</h1>
      <hr>
      <div class="form-group">
        <label for="username"><b>User Name</b></label>
        <input id="username" class = "form-control mb-4" type="text" placeholder="Enter User Name: " name="username" required>
        <label for="psw"><b>Password</b></label>
        <input id="psw" class = "form-control mb-4" type="password" placeholder="Enter Password: " name="password" required>
      </div>
      {% if message %}
        <div class="alert alert-warning">
          {{ message }}
        </div>
      {% endif %}
      <button class="btn btn-primary" type="submit">Login</button>
    </div>
  </form>
{% endblock %}

weather/templates/weather/user_registration.html
{% extends "weather/base.html" %}

{% block content %}
<form class="m-4" action="{% url 'weather:registration' %}" method="post">
    {% csrf_token %}
    <div class="container">
      <h1>Sign Up</h1>
      <hr>
      <div class="form-group">
          <label for="username"><b>User Name</b></label>
          <input type="text" class="form-control mb-4" placeholder="Enter User Name: " name="username" required>
          <label for="firstname"><b>First Name</b></label>
          <input type="text" class="form-control mb-4" placeholder="Enter First Name: " name="firstname" required>
          <label for="lastname"><b>Last Name</b></label>
          <input type="text" class="form-control mb-4" placeholder="Enter Last Name: " name="lastname" required>
          <label for="psw"><b>Password</b></label>
          <input type="password" class="form-control mb-4" placeholder="Enter Password: " name="password" required>
          {% if message %}
          <div class="alert alert-warning">
              {{ message }}
          </div>
          {% endif %}
          <button class="btn btn-primary" type="submit">Sign up</button>
      </div>
    </div>
  </form>
{% endblock %}